export const linksData = [
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Dapatkan Alamat Bisnis Sah", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Eksplorasi Alamat Bisnis", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Lihat Paket VO", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Virtual Office Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Virtual Office Bintaro", "destination": "/virtual-office-bintaro" },
  { "type": "SEO WEAPON PAGE", "source": "app/alamat-bisnis-jakarta-selatan/page.tsx", "anchor": "Harga Virtual Office Jakarta Selatan", "destination": "/harga-virtual-office-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "operasional kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "administrasi perusahaan", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Jadwalkan Survey Gratis", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Lihat Unit Tersedia", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Tentang BBC", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Legalitas Pendirian", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/fasilitas-kantor/page.tsx", "anchor": "Paket Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-sewa-kantor-bintaro/page.tsx", "anchor": "Tanya Harga Spesifik", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-sewa-kantor-bintaro/page.tsx", "anchor": "Tanya Harga & Ketersediaan", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-sewa-kantor-bintaro/page.tsx", "anchor": "Sewa Kantor Jakarta Selatan", "destination": "/sewa-kantor-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-sewa-kantor-bintaro/page.tsx", "anchor": "Kantor Dekat Bintaro Jaya", "destination": "/kantor-dekat-bintaro-jaya" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-sewa-kantor-bintaro/page.tsx", "anchor": "Kantor Dekat Tol Veteran", "destination": "/kantor-dekat-tol-veteran" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Eksplorasi Paket Virtual Office", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Cek Detail Harga & Paket", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Bandingkan Paket Sekarang", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Virtual Office Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Virtual Office Bintaro", "destination": "/virtual-office-bintaro" },
  { "type": "SEO WEAPON PAGE", "source": "app/harga-virtual-office-jakarta-selatan/page.tsx", "anchor": "Alamat Bisnis Jakarta Selatan", "destination": "/alamat-bisnis-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-bintaro-jaya/page.tsx", "anchor": "Eksplorasi Pilihan Kantor", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-bintaro-jaya/page.tsx", "anchor": "Cek Ketersediaan Unit", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-bintaro-jaya/page.tsx", "anchor": "Kantor Dekat Tol Veteran", "destination": "/kantor-dekat-tol-veteran" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-bintaro-jaya/page.tsx", "anchor": "Harga Sewa Kantor Bintaro", "destination": "/harga-sewa-kantor-bintaro" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-bintaro-jaya/page.tsx", "anchor": "Sewa Kantor Jakarta Selatan", "destination": "/sewa-kantor-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-tol-veteran/page.tsx", "anchor": "Cek Lokasi & Unit", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-tol-veteran/page.tsx", "anchor": "Jadwalkan Survey Lokasi", "destination": "/sewa-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-tol-veteran/page.tsx", "anchor": "Kantor Dekat Bintaro Jaya", "destination": "/kantor-dekat-bintaro-jaya" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-tol-veteran/page.tsx", "anchor": "Harga Sewa Kantor Bintaro", "destination": "/harga-sewa-kantor-bintaro" },
  { "type": "SEO WEAPON PAGE", "source": "app/kantor-dekat-tol-veteran/page.tsx", "anchor": "Sewa Kantor Jakarta Selatan", "destination": "/sewa-kantor-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "infrastruktur gedung", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "layanan legalitas", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "alamat bisnis resmi", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Jadwalkan Konsultasi", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Pelajari BBC Lebih Lanjut", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Tentang BBC", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Virtual Office", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/klien-dan-testimoni/page.tsx", "anchor": "Legalitas Usaha", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/cek-kbli/page.tsx", "anchor": "Konsultasi KBLI Profesional", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/cek-kbli/page.tsx", "anchor": "Kembali ke Layanan Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "ruang kantor fisik", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "layanan virtual office Jakarta Selatan", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "Konsultasi Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "Lihat Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "sewa kantor BBC", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "alamat bisnis resmi Jakarta Selatan", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "cek-kbli", "destination": "/legal/cek-kbli" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "pkp-perdagangan", "destination": "/legal/pkp-perdagangan" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "paket virtual office BBC", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "sewa kantor di BBC", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "Konsultasi Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/LegalClient.tsx", "anchor": "Hubungi Tim Legal", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "sewa kantor", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "virtual office", "destination": "/virtual-office" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Virtual Office BBC", "destination": "/virtual-office" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Service Office BBC", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Lihat Paket Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Hub Legalitas PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Virtual Office", "destination": "/virtual-office" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Service Office", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "MONEY PAGE", "source": "app/legal/pendirian-pt-jakarta-selatan/page.tsx", "anchor": "Tentang BBC", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/legal/pkp-perdagangan/page.tsx", "anchor": "Lihat Sewa Kantor &rarr;", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/pkp-perdagangan/page.tsx", "anchor": "Pelajari Layanan &rarr;", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legal/pkp-perdagangan/page.tsx", "anchor": "Konsultasi Legalitas & PKP", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legal/pkp-perdagangan/page.tsx", "anchor": "Kembali ke Layanan Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "penggunaan ruang kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "Pelajari Virtual Office", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "Tentang BBC", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/legalitas-dan-perizinan-bbc/page.tsx", "anchor": "Layanan Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "infrastruktur kantor fisik", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "alamat bisnis resmi", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "legalitas usaha", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "Jadwalkan Kunjungan Survey", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "Tentang BBC", "destination": "/tentang-kami" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "Fasilitas Gedung", "destination": "/fasilitas-kantor" },
  { "type": "OTHERS", "source": "app/lokasi-kantor/page.tsx", "anchor": "Lihat Unit Tersedia", "destination": "/sewa-kantor" },
  { "type": "HUB PAGE", "source": "app/page.tsx", "anchor": "serviced office Bintaro Business Centre", "destination": "/sewa-kantor" },
  { "type": "HUB PAGE", "source": "app/page.tsx", "anchor": "virtual office Jakarta Selatan", "destination": "/virtual-office" },
  { "type": "HUB PAGE", "source": "app/page.tsx", "anchor": "sewa kantor Jakarta Selatan", "destination": "/sewa-kantor/jakarta-selatan" },
  { "type": "HUB PAGE", "source": "app/page.tsx", "anchor": "paket VO Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "HUB PAGE", "source": "app/page.tsx", "anchor": "Hubungi Kami Sekarang", "destination": "/kontak" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "layanan legal pendirian PT Jakarta Selatan", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "sewa kantor Jakarta Selatan", "destination": "/sewa-kantor/jakarta-selatan" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "layanan virtual office Bintaro Business Centre", "destination": "/virtual-office" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "kantor dekat Bintaro Jaya", "destination": "/kantor-dekat-bintaro-jaya" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "kantor dekat tol Veteran", "destination": "/kantor-dekat-tol-veteran" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "harga sewa kantor Bintaro", "destination": "/harga-sewa-kantor-bintaro" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "Fasilitas Gedung", "destination": "/fasilitas-kantor" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "Legalitas & Perizinan", "destination": "/legalitas-dan-perizinan-bbc" },
  { "type": "MONEY PAGE", "source": "app/sewa-kantor/page.tsx", "anchor": "Klien & Testimoni", "destination": "/klien-dan-testimoni" },
  { "type": "OTHERS", "source": "app/sewa-kantor-jakarta-selatan/page.tsx", "anchor": "Cek Pilihan Ruang Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/sewa-kantor-jakarta-selatan/page.tsx", "anchor": "Daftar Harga & Unit", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/sewa-kantor-jakarta-selatan/page.tsx", "anchor": "Jadwalkan Survey", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/sewa-kantor-jakarta-selatan/page.tsx", "anchor": "Harga Sewa Kantor Bintaro", "destination": "/harga-sewa-kantor-bintaro" },
  { "type": "OTHERS", "source": "app/sewa-kantor-jakarta-selatan/page.tsx", "anchor": "Virtual Office Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "layanan virtual office", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "layanan sewa kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "legalitas pendirian perusahaan", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Verifikasi Legalitas Kami", "destination": "/legalitas-dan-perizinan-bbc" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Lihat Layanan Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Info Virtual Office", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Fasilitas Gedung", "destination": "/fasilitas-kantor" },
  { "type": "OTHERS", "source": "app/tentang-kami/page.tsx", "anchor": "Klien & Testimoni", "destination": "/klien-dan-testimoni" },
  { "type": "MONEY PAGE", "source": "app/virtual-office/page.tsx", "anchor": "Service Office", "destination": "/sewa-kantor" },
  { "type": "MONEY PAGE", "source": "app/virtual-office/page.tsx", "anchor": "Jasa Legal Pendirian PT", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "MONEY PAGE", "source": "app/virtual-office/page.tsx", "anchor": "Legalitas & Perizinan", "destination": "/legalitas-dan-perizinan-bbc" },
  { "type": "MONEY PAGE", "source": "app/virtual-office/page.tsx", "anchor": "Tentang Kami", "destination": "/tentang-kami" },
  { "type": "MONEY PAGE", "source": "app/virtual-office/page.tsx", "anchor": "Lokasi & Akses", "destination": "/lokasi-kantor" },
  { "type": "SEO WEAPON PAGE", "source": "app/virtual-office-bintaro/page.tsx", "anchor": "Tanya Ketersediaan Alamat", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/virtual-office-bintaro/page.tsx", "anchor": "Virtual Office Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "SEO WEAPON PAGE", "source": "app/virtual-office-jakarta-selatan/page.tsx", "anchor": "Cek Pilihan Paket Virtual Office", "destination": "/virtual-office" },
  { "type": "SEO WEAPON PAGE", "source": "app/virtual-office-jakarta-selatan/page.tsx", "anchor": "Virtual Office Bintaro", "destination": "/virtual-office-bintaro" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Sewa Kantor", "destination": "/sewa-kantor" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Virtual Office", "destination": "/virtual-office" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Pendirian PT Jakarta Selatan", "destination": "/legal/pendirian-pt-jakarta-selatan" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Sewa Kantor Jakarta Selatan", "destination": "/sewa-kantor/jakarta-selatan" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Virtual Office Jakarta Selatan", "destination": "/virtual-office-jakarta-selatan" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Sewa Kantor Bintaro", "destination": "/sewa-kantor/bintaro" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Virtual Office Bintaro", "destination": "/virtual-office-bintaro" },
  { "type": "OTHERS", "source": "components/navigation/Footer.tsx", "anchor": "Harga Sewa Kantor Bintaro", "destination": "/harga-sewa-kantor-bintaro" }
];
